# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: www.arcton.nz
title: Locatio
email: arctondev@gmail.com
author: Team Arcton
description: Locatio enhances online property listings with local crime statistics, demographics and more, letting you choose a home with peace of mind.
copyright: 'Copyright &copy; 2016 Arcton. Locatio is not affiliated with, authorized by or endorsed by Trade Me.'
credits: 'Theme based on Landing Page by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Install
    icon: chrome
    primary: true
    url: https://chrome.google.com/webstore/detail/locatio/egbmcaagcpgnojkdbgigkdkckabmcgpp
  - title: Github
    icon: github
    url: https://github.com/arcton/locatio-extension
